service: products-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-north-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/Products" # Set AWS Account in lieu of '*' if needed

  environment:
    DDB_AWS_REGION: eu-north-1

package:
  artifact: build/distributions/${self:service}.zip

functions:
  createProduct:
    handler: com.serverless.CreateProductHandler
    events:
      - http:
          method: post
          path: /products
          integration: lambda
          request:
            template:
              application/json: '$input.body'

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
